name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]')
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release /p:EnableWindowsTargeting=true --no-restore

    - name: Publish project
      run: dotnet publish -c Release -o publish /p:EnableWindowsTargeting=true

    - name: Zip published output
      run: Compress-Archive -Path publish\* -DestinationPath myapp.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release build ${{ github.run_number }}
        files: myapp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
